models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo-instruct

# Ex 0
instructions:
    - type: "general"
      content: |
        TODO: Write your applications general instructions here.