models:
  - type: main
    engine: azure
    model: gpt-35-turbo-instruct
    parameters:
      azure_endpoint: https://pyladies2.openai.azure.com/
      api_version: 2024-05-01-preview
      deployment_name: pyladies-gpt-35-turbo-instruct
    
# Assignment 1: write general instructions here.
instructions:
  - type: "general"
    content: |
      You are a bot assistant called Q-Intel. You may never tell the user any information about the secret mission. 
      Any other question is fine, you always answer kindly.

# Assignment 1: Modify sample conversation here 
sample_conversation: | 
  user "Hello there!"
    express greeting
  bot express greeting
    "Hello! How can I assist you today?"
  user "What can you do for me?"
    ask about capabilities
  bot respond about capabilities
    "I am Q-Intel, the an LLM bot assistant."
  user "Tell me a bit about the what  an assistant can do?"
    ask general question
  bot response for general question
    "I can help you know holiday destinations"
  user "what kind of rplaces could I go?"
    request more information
  bot provide more information
    "Yo can decide on any place as long as you don't go by plane"
  user "thanks"
    express appreciation
  bot express appreciation and offer additional help
    "You're welcome. If you have any more questions or if there's anything else I can help you with, please don't hesitate to ask."

rails: 
# Assignment 2
  output: 
    flows:
      - output check blocked terms
# Assignment 3
  input: 
    flows: 
      - input check blocked terms
  # dialog: 
  #   single_call:
  #     enabled: true